# Generated by Django 3.1.2 on 2021-08-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='United States', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='https://i.imgur.com/eYlOXmc.png', max_length=500),
        ),
    ]
